[package]
name = "upstream"
version = "0.1.0"
edition = "2018"

[dependencies]
bevy = { version = "0.5.0", features = ["dynamic", "serialize"] }
serde = "1.0.126"
bincode = "1.3.3"
toml = "0.5.8"
home = "0.5.3"
magic-crypt = "3.1.8"
